# Generated by Django 4.2.7 on 2023-11-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('AuthorName', models.CharField(max_length=100)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=50)),
                ('PublishedDate', models.DateField(blank=True, null=True)),
                ('QuantityAvailable', models.IntegerField()),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('BorrowerID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('CheckoutDate', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('BorrowerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('FineID', models.IntegerField(primary_key=True, serialize=False)),
                ('FineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paid', models.BooleanField()),
                ('TransactionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.transaction')),
            ],
        ),
    ]
